ktor:
  application:
    modules:
      - com.nhom2.ApplicationKt.module
  deployment:
    port: 8080

app:
  seedData: true # Set to true to seed initial data on startup

postgres:
  url: "jdbc:h2:mem:dental_app;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
  user: sa
  password: ""

jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
